---
tasks:
  oss_and_wiki_tasks:
    name: Parse OSS & wiki grades Sheet
    description: Parse OSS & wiki grades Sheet
    subtasks:
      - name: Parse OSS & wiki grades - Spring 22
        path: /Users/chinmay/dev/expertiza/oss-feedback-processor/data/spring-22/oss_and_wiki_grades_spring_2022.xlsx
        url: https://docs.google.com/spreadsheets/d/1qY6wGMAqsA3gnAy2fll6nKq80ghtbUhgT24R2uNSGec/edit#gid=0
        sheet: 0
        feedback_column_names: ['OSS Comments', 'Wiki comments']
        feedback_column_indexes: ['E', 'G']
        resource_column_names: []
        resource_column_indexes: []
        id_column_names: []
        id_column_indexes: ['B']
        enabled: false
      
      - name: Parse OSS & wiki grades - Fall 21
        path: /Users/chinmay/dev/expertiza/oss-feedback-processor/data/spring-22/oss_and_wiki_grades_spring_2022.xlsx
        url: https://docs.google.com/spreadsheets/d/1BgqowvanfrwYZBZN6kIAZHKlDoUGF_CQKhWyFohBYOE/edit#gid=0
        sheet: 0
        feedback_column_names: []
        feedback_column_indexes: ['E', 'G']
        resource_column_names: []
        resource_column_indexes: []
        id_column_names: []
        id_column_indexes: ['B']
        enabled: true
  
  project_demo_eval_tasks:
    name: Parse Project demo evaluation rubric Sheet
    subtasks:
      - name: Parse Project demo evaluation rubric - Spring 22
        path: /Users/chinmay/dev/expertiza/oss-feedback-processor/data/spring-22/project_demo_evaluation_rubric_spring_2022.xlsx
        url: https://docs.google.com/spreadsheets/d/1qY6wGMAqsA3gnAy2fll6nKq80ghtbUhgT24R2uNSGec/edit#gid=0
        sheet: 0
        feedback_column_names: ['Comments to be returned on project', 'Comments on design doc']
        feedback_column_indexes: []
        resource_column_names: []
        resource_column_indexes: []
        id_column_names: []
        id_column_indexes: ['E']
        enabled: true
      
      - name: Parse Project demo evaluation rubric - Fall 21
        path: /Users/chinmay/dev/expertiza/oss-feedback-processor/data/spring-22/project_demo_evaluation_rubric_spring_2022.xlsx
        url: https://docs.google.com/spreadsheets/d/1BgqowvanfrwYZBZN6kIAZHKlDoUGF_CQKhWyFohBYOE/edit#gid=0
        sheet: 0
        feedback_column_names: ['Comments to be returned on project', 'Comments on design doc']
        feedback_column_indexes: ['Q', 'S']
        resource_column_names: []
        resource_column_indexes: []
        id_column_names: ['Project number and name']
        id_column_indexes: []
        enabled: true
  
  project_history_tasks:
    name: Parse Comprehensive Expertiza OSS and Final Project History Sheet
    subtasks:
      - name: Parse Comprehensive Expertiza OSS and Final project history
        path: /Users/chinmay/dev/expertiza/oss-feedback-processor/data/spring-22/comprehensive_expertiza_OSS_and_final_project_history.xlsx
        url: https://docs.google.com/spreadsheets/d/1bUwyvxgWe6hRnUo1FkSz2PdQ6DQELS_VyQ1o8l4L0qM/edit#gid=1868522269
        sheet: 0
        feedback_column_names: ['Feedback on project', 'Feedback on design doc']
        feedback_column_indexes: []
        resource_column_names: ['Submitted Work']
        resource_column_indexes: []
        id_column_names: ['Project ID']
        id_column_indexes: []
        enabled: true
  